# -*- coding: utf-8 -*-
"""Reggresion in KNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JaVWWmR9p1KDtN1OKMIyCbyiYvlyRHze
"""

import pandas as pd
from sklearn.neighbors import KNeighborsRegressor
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_absolute_error, mean_squared_error

insurance = pd.read_csv("https://raw.githubusercontent.com/stedy/Machine-Learning-with-R-datasets/master/insurance.csv")

type(insurance)

insurance

insurance.head(10)

insurance.tail(10)

insurance.info()

insurance.describe()

X = insurance.drop('charges',axis = 1)
X

y = insurance['charges']
y

X.columns

# One-hot encoding
X_encoded = pd.get_dummies(X, columns=['sex','smoker','region'])
X_encoded

X_encoded.info()

X_train,X_test,y_train,y_test = train_test_split(X_encoded,y,test_size = 0.2,random_state = 42)

X_train

y_train

X_test

y_test

knn = KNeighborsRegressor(n_neighbors=5)
knn.fit(X_train,y_train)

# Predictions
y_pred = knn.predict(X_test)
y_pred

mean_absolute_error(y_test, y_pred)

mean_squared_error(y_test, y_pred)

scaler = MinMaxScaler()
scaler.fit(X_train)
X_train_norm=scaler.transform(X_train)
X_test_norm=scaler.transform(X_test)

X_train_norm

X_train

knn = KNeighborsRegressor(n_neighbors=5)
knn.fit(X_train_norm,y_train)

# Predictions
y_pred = knn.predict(X_test_norm)
y_pred

mean_absolute_error(y_test, y_pred)

mean_squared_error(y_test, y_pred)

#self study
# Import seaborn
import seaborn as sns
# Load an example dataset
tips = sns.load_dataset("tips")

tips